# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/XDC.xdc

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/ROM_Gamecover.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Gamecover || ORIG_REF_NAME==ROM_Gamecover} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/ip/ROM_Gamecover_blk_mem_gen_0_0/ROM_Gamecover_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Gamecover_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Gamecover_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/ROM_Background.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Background || ORIG_REF_NAME==ROM_Background} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/ip/ROM_Background_blk_mem_gen_0_0/ROM_Background_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Background_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Background_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/ROM_Mask_normal.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Mask_normal || ORIG_REF_NAME==ROM_Mask_normal} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/ip/ROM_Mask_normal_blk_mem_gen_0_0/ROM_Mask_normal_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Mask_normal_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Mask_normal_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/ROM_Mask_crazy.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Mask_crazy || ORIG_REF_NAME==ROM_Mask_crazy} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/ip/ROM_Mask_crazy_blk_mem_gen_0_0/ROM_Mask_crazy_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Mask_crazy_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Mask_crazy_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/ROM_JOJO_overdrive.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_JOJO_overdrive || ORIG_REF_NAME==ROM_JOJO_overdrive} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/ip/ROM_JOJO_overdrive_blk_mem_gen_0_0/ROM_JOJO_overdrive_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_JOJO_overdrive_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_JOJO_overdrive_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/ROM_JOJO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_JOJO || ORIG_REF_NAME==ROM_JOJO} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/ip/ROM_JOJO_blk_mem_gen_0_0/ROM_JOJO_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_JOJO_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_JOJO_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/ROM_Bubble.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Bubble || ORIG_REF_NAME==ROM_Bubble} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/ip/ROM_Bubble_blk_mem_gen_0_0/ROM_Bubble_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Bubble_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Bubble_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/ROM_Gameover.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Gameover || ORIG_REF_NAME==ROM_Gameover} -quiet] -quiet

# IP: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/ip/ROM_Gameover_blk_mem_gen_0_0/ROM_Gameover_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Gameover_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Gameover_blk_mem_gen_0_0} -quiet] -quiet

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/ROM_Gamecover_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/ROM_Background_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/ROM_Mask_normal_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/ROM_Mask_crazy_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/ROM_JOJO_overdrive_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/ROM_JOJO_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/ROM_Bubble_ooc.xdc

# XDC: C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/ROM_Gameover_ooc.xdc
