# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/JOJO.cache/wt [current_project]
set_property parent.project_path C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/JOJO.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Raymond-Ziyue/Desktop/course/LCDF/Lab/Proj/JOJO/JOJO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/background.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/gamecover.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/jojo.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/jojo_overdrive.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/bubble.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/gameover.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/mask_crazy.coe
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/mask_normal.coe
read_verilog -library xil_defaultlib {
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/B2BCD.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/Clkdiv.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/FSM.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/GUI_Gameover.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/GUI_Heart.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Item_Bubble.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Judge_Collision.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Judge_Grounded.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/LED_display.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/MC14495_ZJU.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Map_Platform.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/P2S_IO.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/PS2.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/hdl/ROM_Background_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Block.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/hdl/ROM_Bubble_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/hdl/ROM_Gamecover_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/hdl/ROM_Gameover_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/hdl/ROM_JOJO_overdrive_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/hdl/ROM_JOJO_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/hdl/ROM_Mask_crazy_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/hdl/ROM_Mask_normal_wrapper.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Wall.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_heart.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_music.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Role_JOJO.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Role_Mask_bottom.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Role_Mask_crazy.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Role_Mask_top.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/VGA.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/music.v
  C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/Top_module.v
}
add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/ROM_Gamecover.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/ip/ROM_Gamecover_blk_mem_gen_0_0/ROM_Gamecover_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gamecover/ROM_Gamecover_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/ROM_Background.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/ip/ROM_Background_blk_mem_gen_0_0/ROM_Background_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Background/ROM_Background_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/ROM_Mask_normal.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/ip/ROM_Mask_normal_blk_mem_gen_0_0/ROM_Mask_normal_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_normal/ROM_Mask_normal_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/ROM_Mask_crazy.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/ip/ROM_Mask_crazy_blk_mem_gen_0_0/ROM_Mask_crazy_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Mask_crazy/ROM_Mask_crazy_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/ROM_JOJO_overdrive.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/ip/ROM_JOJO_overdrive_blk_mem_gen_0_0/ROM_JOJO_overdrive_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO_overdrive/ROM_JOJO_overdrive_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/ROM_JOJO.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/ip/ROM_JOJO_blk_mem_gen_0_0/ROM_JOJO_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_JOJO/ROM_JOJO_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/ROM_Bubble.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/ip/ROM_Bubble_blk_mem_gen_0_0/ROM_Bubble_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Bubble/ROM_Bubble_ooc.xdc]

add_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/ROM_Gameover.bd
set_property used_in_implementation false [get_files -all c:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/ip/ROM_Gameover_blk_mem_gen_0_0/ROM_Gameover_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Rom/ROM_Gameover/ROM_Gameover_ooc.xdc]

read_edif C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Framework/P2S.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/XDC.xdc
set_property used_in_implementation false [get_files C:/Users/Raymond-Ziyue/Desktop/Proj/JOJO/Code/XDC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_module -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
