# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Raymond-Ziyue/Desktop/JOJO/Rom/ROM_Mask_crazy/ip/ROM_Mask_crazy_blk_mem_gen_0_0/ROM_Mask_crazy_blk_mem_gen_0_0.xci
# IP: The module: 'ROM_Mask_crazy_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond-Ziyue/Desktop/JOJO/Rom/ROM_Mask_crazy/ip/ROM_Mask_crazy_blk_mem_gen_0_0/ROM_Mask_crazy_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Mask_crazy_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Raymond-Ziyue/Desktop/JOJO/Rom/ROM_Mask_crazy/ip/ROM_Mask_crazy_blk_mem_gen_0_0/ROM_Mask_crazy_blk_mem_gen_0_0.xci
# IP: The module: 'ROM_Mask_crazy_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond-Ziyue/Desktop/JOJO/Rom/ROM_Mask_crazy/ip/ROM_Mask_crazy_blk_mem_gen_0_0/ROM_Mask_crazy_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Mask_crazy_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
